[package]
name = "realtime-rendering"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.21", features = ["max_level_info"]}
simplelog = "0.12.2"
slint = "1.5.1"

[build-dependencies]
slint-build = "1.5.1"
